services:
  - type: web
    name: sell-sync-pos-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URL
        sync: false
      - key: DATABASE_NAME
        value: sell_sync
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
